### ISSUE TITLE
Creates a broken config (npm install fails)

### ISSUE THREAD

**Issue by kuba-orlik** [eslint/create-config#125] opened 2024-06-08 10:38 UTC
Steps to reproduce:

1. `mkdir repro`
2. `cd repro`
3. `npm init`
4. (fill in the details for npm init)
5. `npm init @eslint/config@latest`
6. Give the following answers: 
```
✔ How would you like to use ESLint? · problems
✔ What type of modules does your project use? · commonjs
✔ Which framework does your project use? · none
✔ Does your project use TypeScript? · typescript
✔ Where does your code run? · browser
The config that you've selected requires the following dependencies:

eslint@9.x, globals, @eslint/js, typescript-eslint
✔ Would you like to install them now? · No / Yes
✔ Which package manager do you want to use? · npm
```

**Expected result**: working config of eslint
**Actual result**: a dependency setup that makes it impossible to install. Running `npm install` gives the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: typescript-eslint@7.12.0
npm ERR! Found: eslint@9.4.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^9.4.0" from the root project
npm ERR!   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm ERR!   node_modules/@eslint-community/eslint-utils
npm ERR!     @eslint-community/eslint-utils@"^4.2.0" from eslint@9.4.0
npm ERR!     @eslint-community/eslint-utils@"^4.4.0" from @typescript-eslint/utils@7.12.0
npm ERR!     node_modules/typescript-eslint/node_modules/@typescript-eslint/utils
npm ERR!       @typescript-eslint/utils@"7.12.0" from typescript-eslint@7.12.0
npm ERR!       node_modules/typescript-eslint
npm ERR!         dev typescript-eslint@"^7.12.0" from the root project
npm ERR!       2 more (@typescript-eslint/eslint-plugin, @typescript-eslint/type-utils)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^8.56.0" from typescript-eslint@7.12.0
npm ERR! node_modules/typescript-eslint
npm ERR!   dev typescript-eslint@"^7.12.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: eslint@8.57.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^8.56.0" from typescript-eslint@7.12.0
npm ERR!   node_modules/typescript-eslint
npm ERR!     dev typescript-eslint@"^7.12.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```

I'm using `npm 8.19.4`

**Comment by mdjermanovic** [comment] 2024-06-10 09:50
I can't reproduce this with npm `10.5.0`. I see the same lines, but as `npm WARN` instead of `npm ERR!`. Can you check if there's a `npm WARN using --force` line after you choose package manager?

```
eslint@9.x, globals, @eslint/js, typescript-eslint
√ Would you like to install them now? · No / Yes
√ Which package manager do you want to use? · npm
☕️Installing...
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
...
```

**Comment by JudgeSansDredd** [comment] 2024-06-17 16:16
I'm seeing identical results to @kuba-orlik while attempting setup with the following settings:
```
❯ npm init @eslint/config@latest
✔ How would you like to use ESLint? · problems
✔ What type of modules does your project use? · esm
✔ Which framework does your project use? · none
✔ Does your project use TypeScript? · typescript
✔ Where does your code run? · browser
The config that you've selected requires the following dependencies:

eslint@9.x, globals, @eslint/js, typescript-eslint
✔ Would you like to install them now? · No / Yes
✔ Which package manager do you want to use? · npm
☕️Installing...

added 86 packages, changed 1 package, and audited 681 packages in 3s
```

If I attempt an `npm install` after this step, I end up with the same dependency tree error.

I've attempted this with npm versions 9.8.1 and 10.7.0 with the same results.

In answer to @mdjermanovic's question, it doesn't appear that `--force` was used in the installation. I should also add that using `--force` does circumvent the issue, and that after the fact it appears to work as expected, so far as I can tell.

**Comment by pr0mming** [comment] 2024-06-17 23:02
Hey guys...

I'm here just to report the same problem, I noticed the error by chance a few minutes ago using this config:

```
"devDependencies": {
    "@eslint/js": "^9.4.0",
    "eslint": "^9.4.0",
    "globals": "^15.4.0",
    "typescript": "^5.2.2",
    "typescript-eslint": "^7.13.0",
    "vite": "^5.2.0"
  }
```

But I fixed the error using theses versions (used in another project without the error):

```
"devDependencies": {
    "@eslint/js": "^9.2.0",
    "eslint": "^8.57.0",
    "globals": "^15.1.0",
    "typescript": "^5.2.2",
    "typescript-eslint": "^7.13.0",
    "vite": "^5.2.0"
  }
```
I think something happend in the `@latest` package...

**Comment by mdjermanovic** [comment] 2024-06-18 07:56
I couldn't reproduce any of these errors. @aladdin-add any ides what could be happening here? Could it be that `npm init @eslint/config@latest` still runs some cached version even though there's `@latest` at the end?

**Comment by aladdin-add** [comment] 2024-06-18 08:08
I was able to repro:

1. `npm i eslint@9.x typescript-eslint -D -f`: no errors
```bash
$ npm i eslint@9.x typescript-eslint -D -f
npm warn using --force Recommended protections disabled.
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: example@1.0.0
npm warn Found: eslint@9.5.0
npm warn node_modules/eslint
npm warn   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
....
```

2. `npm i` => errors:
```bash
npm i
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: typescript-eslint@7.13.1
npm error Found: eslint@9.5.0
npm error node_modules/eslint
npm error   dev eslint@"^9.5.0" from the root project
npm error   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
...
```

users have to use `--force` in every installing. I was wondering if we can suggest adding `force=true` in `.npmrc` to avoid it.

**Comment by aladdin-add** [comment] 2024-06-18 08:09
I was able to repro:

1. `npm i eslint@9.x typescript-eslint -D -f`: no errors
```bash
$ npm i eslint@9.x typescript-eslint -D -f
npm warn using --force Recommended protections disabled.
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: example@1.0.0
npm warn Found: eslint@9.5.0
npm warn node_modules/eslint
npm warn   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
....
```

2. `npm i` => errors:
```bash
$ npm i
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: typescript-eslint@7.13.1
npm error Found: eslint@9.5.0
npm error node_modules/eslint
npm error   dev eslint@"^9.5.0" from the root project
npm error   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
...
```

users have to use `--force` in every installing. I was wondering if we can suggested adding `force=true` in `.npmrc` to avoid it.

**Comment by mdjermanovic** [comment] 2024-06-18 08:18
Ah, so the problem is not that `@eslint/create-config` fails to install dependencies, but that it leaves a setup where when doing `npm install` afterwards, it will fail?

**Comment by aladdin-add** [comment] 2024-06-18 08:23
right!

**Comment by mdjermanovic** [comment] 2024-06-18 08:31
Thanks, I see now that I totally misread the original post.

> if we can suggest adding `force=true` in `.npmrc` to avoid it.

Maybe we could suggest adding [`overrides`](https://github.com/eslint/eslint.org/blob/6530787726dff8e466e062861650b7241eaee57a/package.json#L104-L106) like we did in the eslint.org repo?

**Comment by aladdin-add** [comment] 2024-06-18 08:35
also works for me! 👍

**Comment by mdjermanovic** [comment] 2024-06-18 08:42
Okay, marking as accepted.

**Closed** 2024-06-19 10:24 UTC
Labels: bug, accepted
